### ISSUE TITLE
Display "Unique Rare" rather than "Participation Reward" 

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#5]
Feedback from artists was that they want to display the best version of their artwork on the site for fans to upvote and pick in battle.

**Comment by SathishTeckas** [comment]
This issue is solved by changing in this code
[previous battle](https://github.com/Teckas-Technologies/daily-art-battle/blob/19493ec43d84c579a5ee86e9253b211e5cf3002b/src/components/PreviousBattlesTable.tsx#L6)
[upcoming battle](https://github.com/Teckas-Technologies/daily-art-battle/blob/19493ec43d84c579a5ee86e9253b211e5cf3002b/src/components/UpcomingBattlesTable.tsx#L71)
[current battle](https://github.com/Teckas-Technologies/daily-art-battle/blob/19493ec43d84c579a5ee86e9253b211e5cf3002b/src/components/ArtBattle.tsx#L16)
