### ISSUE TITLE
P3. Programmatically Create the Participation NFTs

### ISSUE THREAD

**Issue by Varatharaj-K** [Teckas-Technologies/daily-art-battle#65]
where the winning image is the focus, it's watermarked with the GFXvs logo, and the loosing image is smaller. 

1024px winning image 
256px wide logo 
256px wide losing image
drop shadow behind logo + losing image
![photo_2024-06-24 11 39 33](https://github.com/Teckas-Technologies/daily-art-battle/assets/36834969/45f50623-f802-412e-b8a4-16ee695b3707)

just as an example, with the idea being the participation prize somehow captures the battle that happened. another idea would be to put names of the people who voted (or gambled the most) too

**Comment by starpause** [comment]
![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/389e0706-1611-411d-86c4-e18a554447be)

part of the reward edition design is to be sure it captures the winner in thumbnail but also makes it obvious there's something to zoom into. influenced by schizo posters, trading cards, analog video synthesis, retro hardware upcycling, and embracing the unabashed beauty of y2k photoshops 

i think as part of the sponsorships it will be possible to sell logo space on  the mint. instead of QR code it can be a brand logo or link. bigger = more money.

**Comment by starpause** [comment]
here's a PNG frame that can be composited on all the generated participation reward nfts

for the looser i was cropping it to 4:3 for the picture-in-picture layout

with the frame PX in mind (1024px square) that's a 400x300 cropped image with it's upper left corner at 600y 600x

![GFXVS_FOREVER_FRAME_COMPOSITE](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/7ef3817c-ccd3-4b94-98f3-68151fb1a555)
